config/routes.rb
RsvpHub::Application.routes.draw do
  get "rsvps/create"

  get "rsvps/destroy"

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
  resources :courses

  post 'courses/:course_id/rsvp' => 'rsvps#create', as: 'rsvp_course'
  delete 'courses/:course_id/rsvp' => 'rsvps#destroy', as: 'rsvp_course'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  attr_accessible :name, :description, :address, :city, :starts_at, :ends_at
  has_and_belongs_to_many :users, join_table: 'rsvps'
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/rsvps.rb
class Rsvps < ActiveRecord::Base
  
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  has_and_belongs_to_many :courses, join_table: 'rsvps'

  def rsvp_for_class(course)
      courses << course unless rsvped_for_class?(course)
  end

  def cancel_rsvp_for_class(course)
    course.delete(course) if rsvped_for_class?(course)
  end

  def rsvped_for_class?(course)
    courses.include? course
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

  private

  def authenticate!
    raise ActionController::RoutingError.new('Not Found') unless current_user
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(params[:course])
    if @course.save
      flash[:success] = "Class created!"
      redirect_to courses_path
    else
      flash[:error] = "Opps something went wrong!..Class not created"
      render :new
    end
  end

  def show
    @course = Course.find(params[:id])
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    if @course.update_attributes(params[:course])
      flash[:success] = 'Successfully updated Course'
      redirect_to courses_path
    else
      flash[:error] = 'Oops, there it is!!...'
      render :edit
    end
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    flash[:success] = 'Successfully deleted Course'
    redirect_to courses_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  before_filter :course
  #before_filter :authenticate!

  def create
    #@course = current_user.courses.build(params[:course])
    if current_user.rsvp_for_class(course)
      message = "You've RSVP'd successfully"
    else
      message = "You've already signed up for this class"
    end

    flash[:success] = message
    redirect_to :back
  end

  def destroy
    if current_user.cancel_rsvp_for_class(course)
      message = "You've cancelled this RSVP successfully"
    else
      message = "You haven't RSVP'd for this class"
    end
    flash[:sucess] = message
    redirect_to :back
  end

  def course
    @course ||= Course.find(params[:course_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rsvps_helper.rb
module RsvpsHelper
end

app/views/courses/_course.html.erb
<section class="courses">
	<h2><%= link_to course.name, course %></h2>

  <h3><%= course.address %>
    <%= ",#{course.city}" %>
  </h3>

  <h3>Date & Time</h3>
  <p>
    <strong>Starts At</strong> <%= course.starts_at %>
    <strong>Ends At</strong> <%= course.ends_at %>
  </p>

  <h3>Description</h3>
  <p><%= course.description %></p>

  <div class="rsvp-info">
    <%= render :partial => 'rsvp', locals: { course: course } %>
  </div>


</section>

app/views/courses/_course_form.html.erb
 	<fieldset>
      <%= form_for @course, :html => { :multipart => true } do |f| %>
    
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :description %>
      <%= f.text_area :description, :size => "20x10", placeholder: "add a description here..." %>

      <%= f.label :address %>
      <%= f.text_field :address %>

      <%= f.label :city %>
      <%= f.text_field :city %> 

      <%= f.label :starts_at %>
      <%= f.text_field :starts_at %> 

      <%= f.label :ends_at %>
      <%= f.text_field :ends_at %> 

      <p class="actions">
        <%= f.submit "Add Class", class: 'btn btn-primary' %>
        <%= link_to 'Cancel', courses_path, class: 'btn' %>
      </p>

      <% end %>

  </fieldset>
      
    </div>

app/views/courses/_rsvp.html.erb
<div class="well">
	<% if current_user && current_user.rsvped_for_class?(course) %>
	<p>You're attending this class</p>
	<p><%= link_to 'Cancel Rsvp', rsvp_course_path(course), class: 'btn btn-danger', method: 'delete' %></p>
	<% else%>
	<p>Would you like to sign up?</p>
	<p><%= link_to 'RSVP for this class', rsvp_course_path(course), class: 'btn btn-success', method: 'post' %></p>
	<% end %>
</div>

app/views/courses/course.html.erb
<section class='courses'>
	<h2><%= course.name %></h2>

	<h3>Location</h3>
	<%= course.address %>

</section>

app/views/courses/edit.html.erb
<h3>Edit Class info</h3>

<%= render 'course_form' %>

app/views/courses/index.html.erb
<div class="courses">
	<h1>Classes</h1>
	<% if @courses.present? %>
		<%= render @courses %>
   
	<% else %>
    <p>Sorry! No Classes </p>
	<% end %>



  <p class="actions">
    <%= link_to 'Add New Class', new_course_path, class: 'btn btn-primary' %>
  </p>
</div>

app/views/courses/new.html.erb
<h1>New Class Form</h1>
   <%= render 'course_form' %>
  

app/views/courses/show.html.erb
<h3>Class</h3>

<%= render @course %>

<div class="rsvp-info">
  <%= render :partial => 'rsvp', locals: { course: course } %>
 </div>

<p class="actions">
  <%= link_to 'Edit', edit_course_path(@course), class: 'btn' %>
  <%= link_to 'Delete', @course, class: 'btn btn-danger', confirm: 'Are you sure?', method: 'delete' %>
 </p>

app/views/home/index.html.erb
<h3>Home</h3>
<% @users.each do |user| %>
  <p>User: <%=link_to user.name, user %></p>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Rsvp Hub", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
    <li>
      <%= link_to "Welcome, #{current_user.email}", '#', class: 'navbar-link' %>
    </li>
    <li>
      <%= link_to 'Courses', courses_path %>
    </li>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Admin', users_path %>
      </li>
    <% end %>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rsvp Hub" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rsvp Hub" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </div>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/rsvps/create.html.erb
<h1>Rsvps#create</h1>
<p>Find me in app/views/rsvps/create.html.erb</p>

app/views/rsvps/destroy.html.erb
<h1>Rsvps#destroy</h1>
<p>Find me in app/views/rsvps/destroy.html.erb</p>

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h3>Users</h3>
<div class="span8">
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Registered</th>
      <th>Role</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at.to_date %></td>
      <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
      <td>
        <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
        <%= render user %>
      </td>
      <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>